### ISSUE TITLE
Multi data source

### ISSUE THREAD

**Issue by VShawn** [1Remote/1Remote#282]
Sometime we need a personal session database + some shared session database for work teams.

- [x] MySQL database supported
- [x] SQLite path editing view
- [x] MySQL config editing view
- [x] Additonal data source control manager
   - ~ data RSA encryption for mysql ~ see #327 
   - [x] Database statue detector (find out if need reload)
   - [x] ~Database statue detector work with ASYNC~
   - [x] reconnect after db config edit
   - [x] A list view of all data source.( add / edit / delete )
- [x] Servers management for multi data source
   - [x] Add new server to assign data source
   - [x] Server list sort by data source
- [x] MySQL access control if if the db user has no write permission (have no insert update privileges)
![image](https://user-images.githubusercontent.com/10143738/196145245-a0078d1a-2756-40d1-9d7d-d8fefd508e59.png)
   - [x] do not allow edit on UI
   - [x] hide edit / delete / copy user name / copy password buttons.
   - [x] do not allow add to this datasource
- [x]  individual profile for additional data source for group deploy purpose
   - [x] profile encryption
- [ ] documents
   - [x] user guide for how to use Chinese
   - [x] user guide for how to use English
   - [ ] show this feature on 1Remote home page (individual case & team shared case)

**Comment by VShawn** [comment]
here comes the list view

![image](https://user-images.githubusercontent.com/10143738/189071593-de4bd843-d947-4179-859a-d51a4ed6256c.png)

**Comment by majkinetor** [comment]
Have you consider something database agnostic? 1RM certainly doesn't require non ANSI SQL.

Using postgresql should be equally easy as mysql and far more sane.

**Comment by VShawn** [comment]
Actually we are required to use MySQL in the develop, so I started with MySQL first, mssql postgresql would be letter.

I trying to use VARCHAR only in create tabel. It would work (to my understanding) with most of the db. 

Not very sure, I'm not expert of Database.

**Comment by majkinetor** [comment]
Yeah, varchar works everywhere but you are limiting yourself if you only use that.

You need check if it is ANSI SQL or use ORM like entity framework.

**Comment by VShawn** [comment]
almost done, @majkinetor you can try this one since you mentioned in https://github.com/1Remote/PRemoteM/issues/76#issuecomment-1246395658

[1Remote alpha.01.zip](https://github.com/1Remote/PRemoteM/files/9843479/1Remote.alpha.01.zip)

**Comment by Wikiphil** [comment]
Hi,
Is this version will be merged with the main? 

I configured my MySQL server and now all my entries are working on it. Pretty easy to configure, I'll try to access from another computer at the same time.

Regards.

**Comment by VShawn** [comment]
Yes, this version will next generation of PRemoteM. But it's not a good choose to use this version, it not stable now： AKA you might lost your data.

I suggest you get build pack from GitHub action artifacts: https://github.com/1Remote/PRemoteM/actions/runs/3806712068

The package I uploaded on Oct 22 is now obsolete.

**Comment by Wikiphil** [comment]
Done! I’ve updated to the latest version. 

Views/Filters in the main windows are betters.

I'll test the readonly. 

Thanks.

**Comment by VShawn** [comment]
@Joly0 You are right, `sharing servers' address only` is not possible for the current data structure.

And if you ask me, I suggest everyone save their own login in the local sqlite db in this case.

Anyhow... We need a user authority management if we are going to satisfy `teams which all share the same servers, but dont share the same login`. This means server-side\ more complex logic control \ management ui \ bla bla bla... That's too much work for me, I won't do that...
