### ISSUE TITLE
Desktop shortcut

### ISSUE THREAD

**Issue by majkinetor** [1Remote/1Remote#439]
After command line options are done (#427) we can have simple UX for creating desktop shortcuts to specific connections.

## Tasks

Create items in

1. [x] Connection context menu (uses ULID command line option)
2. [x] Tag context menu (uses #tag command line option)
1. [x] Bulk options (uses ULID command line options)
2. [x] Craeting desktop short in guidance

Also:

1. [x] each also uses `--start-minimized`
3. [x] shortcut icon is set to that of the connection

**Comment by majkinetor** [comment]
I like it now when you change icon on the desktop shortcut manually and launch the connection, that icon is shown in the taskbar instead of usual 1remote icon.  Makes me thing that we should set the icon of the connection to be the shortcut icon.

Also, don't forget to add `--start-minimized` on those shortcuts.

**Comment by VShawn** [comment]
![image](https://github.com/1Remote/1Remote/assets/10143738/5fd8199a-a4bc-4c78-8481-e29e4015d03d)


Note: since the shortcuts needs a ico file to custom icon, I saved the generated icons to the `./.locality/icons` folder. The number of icons in this folder may increase over time.

**Comment by VShawn** [comment]
I think it's done.

**Comment by majkinetor** [comment]
Can't test it, latest two versions produce error imediatelly upon startup:

<details>

## Environment

|     Component   |                       Version                      |
|:------------------|:--------------------------------------|
|1Remote | `1.0.0-beta.04`(EXE Release)|
|.NET Framework | ``    |
|CLR            | `6.0.18`       |
|OS             | `Windows 10 Pro N 64-bits 10.0.22621.0 (2009)`                  |

## Error Info

Value cannot be null. (Parameter 'path1')

## Stack Trace

```
   at System.IO.Path.Combine(String path1, String path2)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenConnection(String actionInfo) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 85
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenNewConnection(String newConnectionString) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 55
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_OpenConnection(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 166
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_SelfCheck(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 186
   at _1RM.Service.DataSource.DataSourceService.InitLocalDataSource(SqliteSource sqliteConfig) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DataSourceService.cs:line 83
   at _1RM.AppInitHelper.InitOnConfigure() in D:\a\1Remote\1Remote\Ui\AppInit.cs:line 274
   at _1RM.Bootstrapper.Configure() in D:\a\1Remote\1Remote\Ui\Bootstrapper.cs:line 89
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at _1RM.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 58
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## Recent Log 

```
[T:001][17:13:21.608]	`Fatal`		[Bootstrapper.cs(OnUnhandledException:139)]	
> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenConnection(String actionInfo) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 85
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenNewConnection(String newConnectionString) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 55
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_OpenConnection(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 166
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_SelfCheck(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 186
   at _1RM.Service.DataSource.DataSourceService.InitLocalDataSource(SqliteSource sqliteConfig) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DataSourceService.cs:line 83
   at _1RM.AppInitHelper.InitOnConfigure() in D:\a\1Remote\1Remote\Ui\AppInit.cs:line 274
   at _1RM.Bootstrapper.Configure() in D:\a\1Remote\1Remote\Ui\Bootstrapper.cs:line 89
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at _1RM.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 58
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> StackTrace:    at System.IO.Path.Combine(String path1, String path2)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenConnection(String actionInfo) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 85
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenNewConnection(String newConnectionString) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 55
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_OpenConnection(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 166
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_SelfCheck(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 186
   at _1RM.Service.DataSource.DataSourceService.InitLocalDataSource(SqliteSource sqliteConfig) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DataSourceService.cs:line 83
   at _1RM.AppInitHelper.InitOnConfigure() in D:\a\1Remote\1Remote\Ui\AppInit.cs:line 274
   at _1RM.Bootstrapper.Configure() in D:\a\1Remote\1Remote\Ui\Bootstrapper.cs:line 89
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at _1RM.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 58
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[T:001][17:14:16.135]	`Fatal`		[Bootstrapper.cs(OnUnhandledException:139)]	
> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenConnection(String actionInfo) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 85
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenNewConnection(String newConnectionString) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 55
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_OpenConnection(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 166
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_SelfCheck(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 186
   at _1RM.Service.DataSource.DataSourceService.InitLocalDataSource(SqliteSource sqliteConfig) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DataSourceService.cs:line 83
   at _1RM.AppInitHelper.InitOnConfigure() in D:\a\1Remote\1Remote\Ui\AppInit.cs:line 274
   at _1RM.Bootstrapper.Configure() in D:\a\1Remote\1Remote\Ui\Bootstrapper.cs:line 89
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at _1RM.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 58
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> StackTrace:    at System.IO.Path.Combine(String path1, String path2)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenConnection(String actionInfo) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 85
   at _1RM.Service.DataSource.DAO.Dapper.DapperDatabase.OpenNewConnection(String newConnectionString) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DAO\Dapper\DapperDataBase.cs:line 55
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_OpenConnection(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 166
   at _1RM.Service.DataSource.Model.DataSourceBase.Database_SelfCheck(Int32 connectTimeOutSeconds) in D:\a\1Remote\1Remote\Ui\Service\DataSource\Model\DataSourceBase.Source.cs:line 186
   at _1RM.Service.DataSource.DataSourceService.InitLocalDataSource(SqliteSource sqliteConfig) in D:\a\1Remote\1Remote\Ui\Service\DataSource\DataSourceService.cs:line 83
   at _1RM.AppInitHelper.InitOnConfigure() in D:\a\1Remote\1Remote\Ui\AppInit.cs:line 274
   at _1RM.Bootstrapper.Configure() in D:\a\1Remote\1Remote\Ui\Bootstrapper.cs:line 89
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at _1RM.App.OnStartup(StartupEventArgs e) in D:\a\1Remote\1Remote\Ui\App.xaml.cs:line 58
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

</details>

**Comment by VShawn** [comment]
I encountered this issue in my Windows 11 virtual machine (as you can see, the package is marked as not compatible with Win11), but I didn't expect the issue occur on Win10 as well.

The error is localized within the `System.Data.SQLite.dll`, but the parameters passed to it have not been altered. Therefore, I am still unsure the cause of this error 

(FYI recent versions of System.Data.SQLite.dll underwent a few switches: official `System.Data.SQLite.dll` 1.0.117 -> Microsoft `System.Data.SQLite.dll` -> official `System.Data.SQLite.dll` 1.0.118).

**Comment by VShawn** [comment]
plz check the latest one, it works on my Win11 after I switch sqlite lib to official 1.0.117

![image](https://github.com/1Remote/1Remote/assets/10143738/192486ec-dea1-42da-a687-6c3bc8352312)

**Comment by majkinetor** [comment]
That works, tested on both W10 and 11 👍

**Comment by majkinetor** [comment]
Reopning this until docs is done.

**Comment by VShawn** [comment]
simple doc added
