### ISSUE TITLE
Before viewing or exporting passwords, require for Windows hello verification.

### ISSUE THREAD

**Issue by VShawn** [1Remote/1Remote#466]
### Discussed in https://github.com/1Remote/1Remote/discussions/464

Before viewing plain text passwords or exporting passwords in plain text to json, it is require Windows Hello authentication (if supported by the system). 

Note that this ticket does not involve secondary encryption of passwords, and if the database or memory is physically copied, password theft can still occur.

```[tasklist]
### places need Windows Hello
- [x] viewing plain text passwords with click the eye button
- [x] copy plain text passwords from launcher or context menu
- [x] export to json
```

**Comment by VShawn** [comment]
Feasibility experiment demo has been completed: https://github.com/VShawn/WpfWindowsHelloLoginApp

**Comment by VShawn** [comment]
I trying to use Windows Api `CredUIPromptForWindowsCredentials` instead of `Microsoft.Windows.SDK.NET.dll`.

works with win10
fail on win11.

**Comment by bokkoman** [comment]
Needs W11 support.

**Comment by VShawn** [comment]
> Needs W11 support.

it do support:)

**Comment by majkinetor** [comment]
I don't want this, now I can't see password nor I can export. 

![image](https://github.com/1Remote/1Remote/assets/85767/00648863-5f52-4777-8cac-139cb126dffd)

**Comment by VShawn** [comment]
> I trying to use Windows Api `CredUIPromptForWindowsCredentials` instead of `Microsoft.Windows.SDK.NET.dll`.
> 
> works with win10 fail on win11.

The task of importing Windows Hello has been completed. The remaining work needs to be carried out after I finish testing the Windows API, which will be handled as another ticket.

**Comment by bokkoman** [comment]
> > I trying to use Windows Api `CredUIPromptForWindowsCredentials` instead of `Microsoft.Windows.SDK.NET.dll`.
> > works with win10 fail on win11.
> 
> The task of importing Windows Hello has been completed. The remaining work needs to be carried out after I finish testing the Windows API, which will be handled as another ticket.

Which ticket will this be? So i can follow it :)

**Comment by VShawn** [comment]
> 

https://github.com/1Remote/1Remote/issues/484
