### ISSUE TITLE
Ask windows password when Windows Hello is unavailable before sensitive operations

### ISSUE THREAD

**Issue by VShawn** [1Remote/1Remote#484]
```[tasklist]
### Tasks
- [x] Can ask windows password and verify it
- [x] Switch to windows password if Winodws Hello is down.
- [x] offering option to enable / disable the two step verification before sensitive operations
  - [ ] write the setting to somewhere safe
  - [ ] make the setting only readable by the device create it
```

ref:
https://learn.microsoft.com/en-us/dotnet/standard/security/how-to-use-data-protection
https://learn.microsoft.com/en-us/samples/microsoft/windows-universal-samples/passwordvault/
